name: ishsrec

services:

  rabbitmq:
    build: ./infrastructure/rabbitmq
    container_name: ishsrec-rabbitmq
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      - "${RABBITMQ_MQTT_PORT:-1883}:1883"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER:-ishsrec}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS:-ishsrec}"
      RABBITMQ_DEFAULT_VHOST: "${RABBITMQ_DEFAULT_VHOST:-/}"
    networks:
      - ishsrec-net

  resident-db:
    image: postgres:16
    container_name: ishsrec-resident-db
    ports:
      - "${RESIDENT_DB_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: "${RESIDENT_DB_NAME:-residentdb}"
      POSTGRES_USER: "${RESIDENT_DB_USER:-resident}"
      POSTGRES_PASSWORD: "${RESIDENT_DB_PASSWORD:-resident}"
    volumes:
      - resident_db_data:/var/lib/postgresql/data
    networks:
      - ishsrec-net

  gateway-service:
    build: 
      context: ./gateway-service
    container_name: ishsrec-gateway-service
    depends_on:
     - resident-service
    ports:
     - "${GATEWAY_SERVICE_PORT:-8085}:8085"

  resident-service:
    build:
      context: ./resident-service
    container_name: ishsrec-resident-service
    depends_on:
      - resident-db
      - rabbitmq
    environment:
      RESIDENT_DB_URL: "${RESIDENT_DB_URL:-jdbc:postgresql://resident-db:5432/residentdb}"
      RESIDENT_DB_USER: "${RESIDENT_DB_USER:-resident}"
      RESIDENT_DB_PASSWORD: "${RESIDENT_DB_PASSWORD:-resident}"
    ports:
      - "${RESIDENT_SERVICE_PORT:-8081}:8080"
    networks:
      - ishsrec-net

  messages-mongo:
    image: mongo:7
    container_name: ishsrec-messages-mongo
    ports:
      - "${MESSAGES_MONGO_PORT:-27017}:27017"
    volumes:
      - messages_mongo_data:/data/db
    networks:
      - ishsrec-net

  messages-service:
    build:
      context: ./messages-service
    container_name: ishsrec-messages-service
    depends_on:
      - rabbitmq
      - messages-mongo
    environment:
      MESSAGES_MONGO_URI: "${MESSAGES_MONGO_URI:-mongodb://messages-mongo:27017/messagesdb}"
      MESSAGES_MONGO_DB: "${MESSAGES_MONGO_DB:-messagesdb}"
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: "${RABBITMQ_AMQP_PORT:-5672}"
      RABBITMQ_USERNAME: "${RABBITMQ_DEFAULT_USER:-ishsrec}"
      RABBITMQ_PASSWORD: "${RABBITMQ_DEFAULT_PASS:-ishsrec}"
    ports:
      - "${MESSAGES_SERVICE_PORT:-5002}:5000"
    networks:
      - ishsrec-net

  recommender-service:
    build:
      context: ./recommender-service
    container_name: ishsrec-recommender-service
    ports:
      - "${RECOMMENDER_SERVICE_PORT:-5001}:5000"
    networks:
      - ishsrec-net

networks:
  ishsrec-net:
    driver: bridge

volumes:
  resident_db_data:
  messages_mongo_data:
  