server:
  port: 8085

services:
  resident:
    base-url: http://resident-service:8080
  # messages:
  #   base-url: http://messages-service:5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

