listeners.tcp.default = 5672
management.tcp.port = 15672

mqtt.listeners.tcp.default = 1883
mqtt.allow_anonymous = true

mqtt.vhost = /
mqtt.exchange = amq.topic
management.load_definitions = /etc/rabbitmq/definitions.json

log.console.level = debug

mqtt.prefetch = 10